---
permalink: task-download-the-open-virtual-appliance.html 
sidebar: sidebar 
keywords: download, open virtual appliance 
summary: 'Descargue el dispositivo Open Virtual Appliance (OVA) en VMware vCenter 8,0 y versiones posteriores para implementar el backup y la recuperación de BlueXP en máquinas virtuales.' 
---
= Descargue Open Virtual Appliance
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descargue el dispositivo Open Virtual Appliance (OVA) en VMware vCenter 8,0 y versiones posteriores para implementar el backup y la recuperación de BlueXP en máquinas virtuales.

.Antes de empezar
Si el OVA firmado por el certificado Entrust no es de confianza, asegúrese de instalar y añadir certificados intermedios en el para vCenter.

.Pasos
. Para descargar backup y recuperación de BlueXP para VMs OVA:
+
.. Inicie sesión en la https://mysupport.netapp.com/products/index.html["Sitio de soporte de NetApp"^]
.. En la lista de productos, selecciona *Copia de seguridad y recuperación de BlueXP para VM*, luego haz clic en el botón *Descargar última versión*.
.. Descarga el backup y recuperación de datos de BlueXP para máquinas virtuales `.tar` archivar en cualquier ubicación.


. Extraiga el contenido del archivo tar. El archivo tar contiene el OVA y la carpeta certs. La carpeta certs contiene certificados intermedios.
. En vSphere Client, vaya a *Administration > Certificates > Certificate Management*.
. Junto a *Certificados raíz de confianza*, haz clic en *Agregar*.
+

NOTE: De manera predeterminada, se instala el certificado raíz.

+
.. Vaya a la carpeta certs.
.. Seleccione los certificados intermedios.
.. Instale cada certificado de uno en uno.


. Los certificados se agregan a un panel en Certificados raíz de confianza.
+
Una vez instalados los certificados, OVA puede verificarse e implementarse.



[NOTE]
====
Si el OVA descargado no está alterado, la columna Publisher muestra Certificado de confianza.

====