---
permalink: task-restore-virtual-machines-from-amazon-fsx.html 
sidebar: sidebar 
keywords: restore, virtual machines, amazon fsx 
summary: Al restaurar una máquina virtual, puede sobrescribir el contenido existente con la copia de seguridad que seleccione o puede realizar una copia de la máquina virtual. 
---
= Restaura máquinas virtuales desde Amazon FSx
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al restaurar una máquina virtual, puede sobrescribir el contenido existente con la copia de seguridad que seleccione o puede realizar una copia de la máquina virtual.

Es posible restaurar máquinas virtuales en las siguientes ubicaciones:

* Restaurar a la ubicación original
+
** En el almacén de datos original montado en el host ESXi original (esto sobrescribe la máquina virtual original)


* Restauración para cambio de ubicación
+
** En un almacén de datos diferente montado en el host ESXi original
** En el almacén de datos original montado en un host ESXi diferente gestionado por la misma instancia de vCenter
** En un almacén de datos diferente montado en un host ESXi diferente gestionado por la misma instancia de vCenter
** En un almacén de datos diferente montado en un host ESXi diferente gestionado por una instancia diferente de vCenter en modo vinculado




.Antes de empezar
* Debe existir un backup.
+
Debe haber creado un backup de la máquina virtual mediante el backup y la recuperación de BlueXP para máquinas virtuales para poder restaurar la máquina virtual.

+
[NOTE]
====
Las operaciones de restauración no pueden finalizar correctamente si hay copias Snapshot de la máquina virtual realizadas mediante un software distinto al backup y recuperación de BlueXP para máquinas virtuales.

====
* La máquina virtual no debe estar en tránsito.
+
La máquina virtual que desea restaurar no debe estar en un estado de vMotion o Storage vMotion.

* Errores de configuración DE ALTA disponibilidad.
+
Compruebe que no se muestren errores de configuración de alta disponibilidad en la pantalla vCenter ESXi Host Summary antes de restaurar los backups a una ubicación diferente.



.Acerca de esta tarea
* Se cancela el registro de la máquina virtual y se vuelve a registrar.
+
La operación de restauración de máquinas virtuales cancela el registro de la máquina virtual original, restaura la máquina virtual desde una copia de Snapshot de backup y registra la máquina virtual restaurada con el mismo nombre y la misma configuración en el mismo servidor ESXi. Las máquinas virtuales deben añadir manualmente a los grupos de recursos después de la restauración.

* Restauración de almacenes de datos
+
No es posible restaurar un almacén de datos, pero sí es posible restaurar cualquier máquina virtual incluida en ese almacén de datos.

* Fallos de snapshots de consistencia de VMware para una máquina virtual.
+
Aunque una snapshot de consistencia de VMware arroje un fallo para una máquina virtual, el backup de la máquina virtual se efectúa de todas formas. Puede visualizar las entidades incluidas en la copia de backup por medio del asistente Restore y usarlo para operaciones de restauración.



.Pasos
. En la barra de herramientas del cliente VMware vSphere, haga clic en * Host and Clusters * y, a continuación, seleccione el sistema de almacenamiento.
. En el panel de navegación de la izquierda, haga clic con el botón derecho en una *Virtual Machine*, luego seleccione *BlueXP backup and recovery for VMs* en la lista desplegable y, a continuación, seleccione *Restore* para iniciar el asistente.
. En el asistente *Restaurar*, en la página *Seleccionar copia de seguridad*, seleccione la copia Snapshot de copia de seguridad que desea restaurar.
+
Puede buscar por un nombre de backup específico o un nombre de backup parcial y también puede filtrar la lista de backups haciendo clic en el icono de filtro y seleccionando un intervalo de fechas y horas. Además, debe seleccionar si desea backups que contengan snapshots de VMware, si desea visualizar backups montados y la ubicación. Haga clic en *Aceptar* para volver al asistente.

. En la página *Select Scope*, seleccione *Whole Virtual Machine* en el campo *Restore Scope*, luego seleccione la ubicación de restauración y, a continuación, introduzca la información de destino donde se debe montar la copia de seguridad.
+
En el campo VM name, si existe el mismo nombre de VM, el nuevo formato de nombre de VM es '<vm_name>_<timestamp>'.

+
Al restaurar copias de seguridad parciales, la operación de restauración omite la página *Select Scope*.

. Active la casilla de verificación *Restart VM* si desea que la máquina virtual se encienda después de la operación de restauración.
. En la página *Seleccionar ubicación*, seleccione la ubicación del almacén de datos restaurado.
. Revise la página *Resumen* y luego haga clic en *Finalizar*.
. *Opcional*: Monitorea el progreso de la operación haciendo clic en *Tareas recientes* en la parte inferior de la pantalla.


.Después de terminar
* Agregar máquinas virtuales restauradas a grupos de recursos.
+
Asegúrese de que la máquina virtual recién restaurada esté protegida. Si no lo está, protéjala añadiendo manualmente la máquina virtual restaurada a los grupos de recursos correspondientes.


