---
permalink: task-access-rest-apis.html 
sidebar: sidebar 
keywords: access REST APIs, REST APIs 
summary: Ejecute estos pasos para acceder a las API DE REST. 
---
= Acceda a las API DE REST a través de la página web de API de Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las API DE REST se exponen a través de la página web de Swagger. Puede acceder a la página web de Swagger para mostrar el backup y recuperación de BlueXP para API DE REST DE máquinas virtuales.

.Antes de empezar
Para el backup y la recuperación de datos DE BlueXP para las API de REST DE máquinas virtuales, debes conocer la dirección IP o el nombre de host del dispositivo de backup y recuperación de BlueXP para máquinas virtuales.


NOTE: El plugin solo admite API DE REST con el fin de integrarse con aplicaciones de terceros y no admite cmdlets de PowerShell o CLI.

.Pasos
. Desde un explorador, introduzca la URL para acceder a la página web del plugin de Swagger:
+
https://<OVA_IP>/api/swagger-ui/index.html[]

+

NOTE: No utilice los siguientes caracteres en la dirección URL de la API DE REST: +, . , %, y &.

+
*ejemplo*

+
Acceda al backup y recuperación de datos DE BlueXP para máquinas virtuales API de REST:

+
https://<OVA_IP>/api/swagger-ui/index.html[]

+
Inicie sesión con el mecanismo de autenticación de vCenter para generar el token.

. Haga clic en un tipo de recurso de la API para mostrar las API en ese tipo de recurso.

